# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adr < Formula
  desc ""
  homepage "https://github.com/maximilian-krauss/roehrich"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maximilian-krauss/roehrich/releases/download/0.0.14/roehrich_Darwin_x86_64.tar.gz"
      sha256 "a4b31676ee4be2eafe8ba861ce2d66950b1ad010f463b8c38287788ed3ffabc5"

      def install
        bin.install "roehrich"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maximilian-krauss/roehrich/releases/download/0.0.14/roehrich_Darwin_arm64.tar.gz"
      sha256 "e0c34a23021e550aa7e691a51d01ae45a7799f2fdff854b16ee2af816ff3c07e"

      def install
        bin.install "roehrich"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maximilian-krauss/roehrich/releases/download/0.0.14/roehrich_Linux_x86_64.tar.gz"
        sha256 "a86b794c1776b698938dd12a94690102cad3921b25e63c9706d3311af3c2ae9c"

        def install
          bin.install "roehrich"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maximilian-krauss/roehrich/releases/download/0.0.14/roehrich_Linux_arm64.tar.gz"
        sha256 "9849c0f64b0307b82d4f2b3fd9a38e0bcc0b0ab1c36ebd8d9a72a1e91424c8ba"

        def install
          bin.install "roehrich"
        end
      end
    end
  end
end
