# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roehrich < Formula
  desc ""
  homepage "https://github.com/maximilian-krauss/roehrich"
  version "0.0.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maximilian-krauss/roehrich/releases/download/0.0.15/roehrich_Darwin_x86_64.tar.gz"
      sha256 "2102c90abf676c86f433481bca59eae5bd9e9846a9c9159379345c4a11323788"

      def install
        bin.install "roehrich"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maximilian-krauss/roehrich/releases/download/0.0.15/roehrich_Darwin_arm64.tar.gz"
      sha256 "8e9b4ac5ceba6718d3caba07713e38e00d491445cb806708e6edf0f91b7c4f2b"

      def install
        bin.install "roehrich"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maximilian-krauss/roehrich/releases/download/0.0.15/roehrich_Linux_x86_64.tar.gz"
        sha256 "9978c8b3458952eaf864eec33deeef2de3e93726c5a653f211c653f89cecc850"

        def install
          bin.install "roehrich"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maximilian-krauss/roehrich/releases/download/0.0.15/roehrich_Linux_arm64.tar.gz"
        sha256 "c8ce8ee2a8cdf17e4f9fd494c65026f61bc66cc21353ef205d90d407712cb655"

        def install
          bin.install "roehrich"
        end
      end
    end
  end
end
